# Cloudflare Pages deployment configuration for HonestInvoice
name = "honestinvoice"
compatibility_date = "2024-08-15"
pages_build_output_dir = "dist"

[build]
command = "npm run build"

# Redirect www to non-www (industry standard)
[[redirects]]
from = "https://www.honestinvoice.com/*"
to = "https://honestinvoice.com/:splat"
status = 301

# SPA routing - must be last
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[env.production]
vars = { NODE_ENV = "production", VITE_SUPABASE_URL = "https://ezdmasftbvaohoghiflo.supabase.co", VITE_SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6ZG1hc2Z0YnZhb2hvZ2hpZmxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NDg1MDcsImV4cCI6MjA3MDUyNDUwN30.ftjY1OgDM3MftuplHE3vf_ht-k2M8FeT0_gGcMEXWtc" }

[env.preview]
vars = { NODE_ENV = "preview" }