# Cloudflare Pages deployment configuration for HonestInvoice
name = "honestinvoice"
compatibility_date = "2024-08-15"

# Build and output configuration
[build]
command = "npm install"
command = "npm run build"
publish = "dist"

# Environment variables for production
[env.production.vars]
NODE_ENV = "production"

# Environment variables for preview
[env.preview.vars]
NODE_ENV = "preview"
